apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  namespace: container-swap-demo # Ensure this matches the Argo CD app's destination namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      initContainers:
      - name: template-processor
        image: argodemoacr.azurecr.io/nginx:1.0  # Change tag to red/green/blue as needed
        command: ['sh', '-c', 'envsubst < /template/index.html.template > /shared/index.html']
        volumeMounts:
        - name: template-volume
          mountPath: /template
        - name: html-volume
          mountPath: /shared
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: template-volume
        configMap:
          name: nginx-configmap
      - name: html-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: container-swap-demo # Ensure this matches the Argo CD app's destination namespace
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort # Or ClusterIP if you don't need external access
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: container-swap-demo # Ensure this matches the Argo CD app's destination namespace
data:
  index.html.template: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Nginx!</title>
      <style>
        body {
          background-color: ${Background};
          margin: 0;
          height: 100vh;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          color: white;
          font-size: xx-large;
          font-family: 'Helvetica Neue', Helvetica, 'Lucida Grande', sans-serif;
        }
      </style>
    </head>
    <body>
      <h1>Good Chat from Kubernetes and ArgoCD!</h1>
    </body>
    </html>
